---
- name: Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Remove all PHP package before install PHP version {{ PHP_VERSION }}
  apt:
    name: php?.?
    state: absent

- name: install PHP version {{ PHP_VERSION }}
  apt:
    pkg:
      - php{{ PHP_VERSION }}
      - php{{ PHP_VERSION }}-fpm
      - php{{ PHP_VERSION }}-mbstring
  #    - php{{ PHP_VERSION }}-mcrypt No for php 7.2
      - php{{ PHP_VERSION }}-mysql
      - php{{ PHP_VERSION }}-xml
      - php{{ PHP_VERSION }}-mysqli
      - php{{ PHP_VERSION }}-cli
      - php{{ PHP_VERSION }}-mail #in Test
    update_cache: yes
